#
# Splunk app configuration file
#
[package]
id = Splunk_AI_Assistant_Cloud
check_for_updates = true

[install]
is_configured = false
build = e7f0fed
state_change_requires_restart = false

[ui]
is_visible = 1
label = Splunk AI Assistant

[launcher]
author = Splunk, Inc.
description = Splunk AI Assistant
version = 2.0.0

[triggers]
reload.splunkaiassistant = simple
reload.saiafieldsummary = simple
reload.saiaknowledgeobjsummary = simple
reload.saiamacrossummary = simple
reload.logging = simple
reload.server = simple
reload.infra = simple

[id]
version = 2.0.0
