# chat history
[saia_collection]
enforceTypes = true
field.saia_user = string
field.chat_history = string

# chat history v2
[saia_collection_v2]
enforceTypes = true
field.saia_user = string
field.chat_history = string
accelerated_fields.saia_user_acceleration = {"saia_user": "1"}

# SAIA tool scratchpad
[saia_tool_scratchpad]
field.saia_user = string
field.content = string
field.state = string
field.last_updated = number

# Collection for async jobs (streaming requests to SCS)
[saia_job_map]
enforceTypes = true
field.job_payload = string
field.job_status = string
field.last_updated = number
accelerated_fields.saia_user_acceleration = {"job_status": "1"}

# personalization RBAC object
[saia_allowed_data]
enforceTypes = true
field.saia_user = string
field.allowed_obj = string

# feature flag settings
[saia_metadata]
enforceTypes = true
field.version_info = string
field.feature_settings = string
field.last_updated = string

# telemetry toggle
[saia_settings]
enforceTypes = true
field.ai_service_data_enabled = string
field.permanently_disable_ai_service_data = string

# feature flag settings v2
[saia_settings_v2]
enforceTypes = true
field.enabled = bool
field.additional = string


[saia_field_summary_state]
enforceTypes = true
field.index = string
field.sourcetype = string
field.last_sampled = number
field.latest_time = number

# personalization and optimization flag settings
[saia_popup_collection]
enforceTypes = true
field.shownPersonalization = bool
field.shownModal = bool

# cloud connected configurations
[cloud_connected_configurations]
enforceTypes = true
field.scs_region = string
field.encoded_onboarding_data = string
field.last_setup_timestamp = string
field.scs_token = string
field.scs_token_expiry = string
field.service_principal = string
field.tenant_hostname = string
field.tenant_name = string

# cloud connected proxy settings
[cloud_connected_proxy_settings]
enforceTypes = true
field.proxy_enabled = string
field.proxy_type = string
field.proxy_hostname = string
field.proxy_port = string
field.proxy_auth_enabled = string
field.proxy_username = string

# lookup for macros data
[saia_macros]
enforceTypes = true
field.title = string
field.definition = string
field.content = string
field.macros_used = string
field.updated_spl = string
field.datamodels_used = string
field.lookups_used = string
field.app_name = string
field.args = string
field.user_id = string

# lookup for lookups data
[saia_lookups]
enforceTypes = true
field.title = string
field.type = string
field.fields_list = string
field.app_name = string
field.user_id = string

# lookup for data models data
[saia_datamodels]
enforceTypes = true
field.data_model = string
field.name = string
field.display_name = string
field.parent = string
field.lineage = string
field.type = string
field.is_child = string
field.updated_spl_query = string
field.fields = string
field.macros_used = string
field.datamodels_used = string
field.lookups_used = string
field.group_by = string
field.objects_to_group = string
field.app_name = string
field.user_id = string
field.acceleration = string
