[saia_macros]
collection = saia_macros
external_type = kvstore
fields_list = title, definition, content,macros_used, updated_spl, datamodels_used, lookups_used, app_name, args, user_id

[saia_lookups]
collection = saia_lookups
external_type = kvstore
fields_list = title, type, fields_list, app_name, user_id

[saia_datamodels]
collection = saia_datamodels
external_type = kvstore
fields_list = data_model, name, display_name, parent, lineage, type, is_child, updated_spl_query, fields, macros_used, datamodels_used, lookups_used, group_by, objects_to_group, app_name, user_id, acceleration