[launcher]
description = AI Toolkit
author = Splunk
version = 5.7.4

[package]
id = Splunk_ML_Toolkit

[install]
build = 1779266965872

[ui]
is_visible = 1
label = AI Toolkit
attribution_link = http://docs.splunk.com/Documentation/MLApp/latest/User/Thirdpartysoftwarecredits

[triggers]
reload.algos = simple
reload.experiments = simple
reload.mlspl = simple
reload.scorings = simple
reload.docker_images = simple
reload.dsdl_container = simple
reload.container_connections = simple

[id]
version = 5.7.4
