#   Version 9.0.2
#
# This is an example authorize.conf.  Use this file to configure roles and
# capabilities.
#
# To use one or more of these configurations, copy the configuration block
# into authorize.conf in $SPLUNK_HOME/etc/system/local/.  You must reload
# auth or restart Splunk to enable configurations.
#
# To learn more about configuration files (including precedence) please see
# the documentation located at
# http://docs.splunk.com/Documentation/Splunk/latest/Admin/Aboutconfigurationfiles
# user with mltk_model_admin role is allowed to upload onnx model file of specified size limit and
# create a lookup entry definition for the model file.
[capability::upload_onnx_model_file]
[capability::apply_ai_commander_command]
[capability::edit_ai_commander_config]
[capability::list_ai_commander_config]
[capability::edit_agent_connections]
[capability::run_agents]
[capability::list_container_connections]
[capability::setup_container_configuration]
[capability::enable_hpa]
[capability::list_containers]
[capability::control_containers]
[capability::fit_mltkcontainer]
[capability::apply_mltkcontainer]
[capability::edit_endpoints]
[capability::aitk_ctsm_opt_out]


[role_mltk_admin]
apply_ai_commander_command = enabled
edit_ai_commander_config = enabled
list_ai_commander_config = enabled
upload_lookup_files = enabled
upload_onnx_model_file = enabled
edit_agent_connections = enabled
run_agents = enabled
edit_endpoints = enabled
edit_storage_passwords = enabled
list_storage_passwords = enabled
aitk_ctsm_opt_out = enabled
list_container_connections = enabled
setup_container_configuration = enabled
enable_hpa = enabled
list_containers = enabled
control_containers = enabled
fit_mltkcontainer = enabled
apply_mltkcontainer = enabled

[role_sc_admin]
apply_ai_commander_command = enabled
edit_ai_commander_config = enabled
list_ai_commander_config = enabled
upload_lookup_files = enabled
upload_onnx_model_file = enabled
edit_agent_connections = enabled
run_agents = enabled
edit_endpoints = enabled
edit_storage_passwords = enabled
list_storage_passwords = enabled
aitk_ctsm_opt_out = enabled
list_container_connections = enabled
setup_container_configuration = enabled
enable_hpa = enabled
list_containers = enabled
control_containers = enabled
fit_mltkcontainer = enabled
apply_mltkcontainer = enabled

[role_dsdl_admin]
list_container_connections = enabled
setup_container_configuration = enabled
enable_hpa = enabled
list_containers = enabled
control_containers = enabled
fit_mltkcontainer = enabled
apply_mltkcontainer = enabled

[role_mltk_dsdl_admin]
apply_ai_commander_command = enabled
edit_ai_commander_config = enabled
list_ai_commander_config = enabled
list_container_connections = enabled
setup_container_configuration = enabled
enable_hpa = enabled
list_containers = enabled
control_containers = enabled
fit_mltkcontainer = enabled
apply_mltkcontainer = enabled

[role_mltk_model_admin]
apply_ai_commander_command = enabled
edit_ai_commander_config = enabled
list_ai_commander_config = enabled
upload_lookup_files = enabled
upload_onnx_model_file = enabled
edit_agent_connections = enabled
run_agents = enabled
edit_endpoints = enabled
edit_storage_passwords = enabled
list_storage_passwords = enabled
aitk_ctsm_opt_out = enabled