[dependency_checker]

[last_installed_version]
enforceTypes = true
field.version = string

[showcase_forecast_history]
enforceTypes = true
field._time = time
field.search_query = string
field.field_to_predict = string
field.method = string
field.withhold = number
field.future_values = number
field.period = number
field.confidence_interval = number
field.r_squared = string
field.rmse = string
field.outliers_count = number

[showcase_linear_regression_history]
enforceTypes = true
field.search_query = string
field.earliest_time = string
field.latest_time = string
field.preprocess_query = string
field.regression_algorithm = string
field.regression_algorithm_params = string
field.target = string
field.features = string
field.training_fraction = number
field.model_name = string
field._time = time
field.r_squared = number
field.rmse = number

[showcase_classification_history]
enforceTypes = true
field.search_query = string
field.earliest_time = string
field.latest_time = string
field.preprocess_query = string
field.classification_algorithm = string
field.classification_algorithm_params = string
field.target = string
field.features = string
field.training_fraction = number
field.model_name = string
field._time = time
field.precision = number
field.recall = number
field.accuracy = number
field.f1 = number

[showcase_outlier_detection_history]
enforceTypes = true
field._time = time
field.search_query = string
field.earliest_time = string
field.latest_time = string
field.outlier_variable = string
field.threshold_method = string
field.threshold_multiplier = number
field.window_size = number
field.use_current_point = bool
field.outliers_count = number
field.split_by_fields = string

[showcase_categorical_outlier_detection_history]
enforceTypes = true
field._time = time
field.search_query = string
field.earliest_time = string
field.latest_time = string
field.anomaly_fields = string
field.outliers_count = number

[showcase_clustering_history]
enforceTypes = true
field._time = time
field.search_query = string
field.earliest_time = string
field.latest_time = string
field.apply_ss = bool
field.preprocessed_variable = string
field.apply_dr = bool
field.dr_method = string
field.dr_num = number
field.preprocess_query = string
field.algorithm = string
field.algorithm_params = string
field.cluster_variable = string
field.cluster_model_name = string

[experiment_history]

[mltk_ai_commander_collection]

[aitk_mcp_collection]
enforceTypes = true
field.name             = string
field.description      = string
field.type             = string
field.created_at       = time
field.last_updated_at  = time
field.last_updated_by  = string
accelerated_fields.name = {"name": 1}

[aitk_vector_store_collection]
enforceTypes = true
field.name        = string
field.description = string
field.type        = string
field.created_at       = time
field.last_updated_at  = time
field.last_updated_by  = string
accelerated_fields.name = {"name": 1}

[aitk_agent_collection]
enforceTypes = true
field.name        = string
field.description = string
field.runtime_type = string
accelerated_fields.name = {"name": 1}


[aitk_llm_connection]
enforceTypes = true
field.name = string
field.provider = string
field.model = string
field.is_custom = bool
field.created_at = time
field.updated_by = string
field.updated_at = time
field.created_by = string
accelerated_fields.accel_name = {"name": 1}  
accelerated_fields.accel_provider_model = {"provider": 1, "model": 1}  

[aitk_llm_default_mappings]
enforceTypes = true
field.name = string
field.user = string
accelerated_fields.name = {"name": 1}
accelerated_fields.user = {"user": 1}