[fit]
filename = fit.py
chunked = true
python.version = python3
is_risky = true
python.required=3.13

[apply]
filename = apply.py
chunked = true
python.version = python3
python.required=3.13

[score]
filename = score.py
chunked = true
python.version = python3
python.required=3.13

[summary]
filename = summary.py
chunked = true
python.version = python3
python.required=3.13

[listmodels]
filename = list.py
chunked = true
python.version = python3
python.required=3.13

[deletemodel]
filename = delete.py
chunked = true
python.version = python3
is_risky = true
python.required=3.13

[sample]
filename = sample.py
chunked = true
python.version = python3
python.required=3.13

[kvstorelookup]
filename = kvstorelookup.py
chunked = true
python.version = python3
python.required=3.13

[logexperiment]
filename = logexperiment.py
chunked = true
local = true
python.version = python3
python.required=3.13

[ai]
filename = ai.py
streaming = true
chunked = true
python.version = python3
is_risky = true
python.required=3.13

[agentstatus]
filename = agent_status.py
streaming = true
chunked = true
python.version = python3
is_risky = true
python.required=3.13

[aiagent]
filename = ai_agent.py
streaming = true
chunked = true
python.version = python3
is_risky = true
maxwait = 1500
run_in_preview = false
enableheader = false
requires_srinfo = true
supports_getinfo = false
python.required=3.13
