[golden-cpu]
title = Golden Image CPU (5.2.1)
image = mltk-container-golden-cpu:5.2.1
repo = splunk/
runtime = none

[golden-cpu-arm]
title = Golden Image ARM64 (5.2.1)
image = mltk-container-golden-cpu:5.2.1-arm64
repo = splunk/
runtime = none

[golden-gpu]
title = Golden Image GPU (5.2.1)
image = mltk-container-golden-gpu:5.2.1
repo = splunk/
runtime = none,nvidia

[golden-cpu-transformers]
title = Transformers CPU (5.2.1)
image = mltk-container-golden-cpu-transformers:5.2.1
repo = splunk/
runtime = none

[golden-gpu-transformers]
title = Transformers GPU (5.2.1)
image = mltk-container-golden-gpu-transformers:5.2.1
repo = splunk/
runtime = none,nvidia

[golden-gpu-rapids]
title = Rapids 24.08 (5.2.1)
image = mltk-container-golden-gpu-rapids:5.2.1
repo = splunk/
runtime = none,nvidia

[llm-rag]
title = Red Hat LLM RAG CPU (5.2.1)
image = mltk-container-ubi-llm-rag:5.2.1
repo = splunk/
runtime = none

[escu-cpu]
title = ESCU (5.2.1)
image = mltk-container-escu-cpu:5.2.1
repo = splunk/
runtime = none

[spark]
title = Spark 3.5.1 (5.2.1)
image = mltk-container-spark:5.2.1
repo = splunk/
runtime = none

[ai-investigator]
title = AI Investigator Beta (5.2.1)
image = mltk-container-ubi-llm-rag:ai-investigator-beta-1.0.0
repo = splunk/
runtime = none
