[OutliersViz]
label = Outliers Chart
description = Show the acceptable range for a value and highlight points outside that range.
search_fragment = | table _time, <outlier_variable>, <lower_bound>, <upper_bound>
default_height = 400

[ForecastViz]
label = Forecast Chart
default_height = 400
description = Show the output of the "predict" command.
search_fragment = | timechart count [by comparison_category] | `modvizpredict(<field>, <algorithm>, <future_timespan>, <holdback>, <confidence_interval>)`

[ScatterLineViz]
label = Scatter Line Chart
default_height = 400
description = Show relationships between discrete values in two dimensions, as well as an additional identity (x=y) line.
search_fragment = | table <x_axis> <y_axis>

[HistogramViz]
label = Histogram Chart
default_height = 400
description = Show continuous data bucketed by the bucket/bin command.
search_fragment = | `histogram(<field, bins>)`

[LinesViz]
label = Downsampled Line Chart
default_height = 400
description = Show values and trends over time, utilizing downsampling to show large numbers of points.
search_fragment = | table <x_axis> <y_axis_1> <y_axis_2> ...

[ScatterplotMatrixViz]
label = Scatterplot Matrix
default_height = 600
description = Show relationships between discrete values in multiple dimensions.
search_fragment = | table <name_category>, <dimension_1>, <dimension_2>, <dimension_3> ...

[BoxViz]
label = Boxplot Chart
default_height = 400
description = Shows the minimum, lower quartile, median, upper quartile, and maximum of each field.
search_fragment = | `boxplot`

[Scatter3dViz]
label = 3D Scatterplot
default_height = 600
description = Show relationships between discrete values in a three dimensional representation.
search_fragment = | table clusterId x y z [clusterColor]

[DistributionViz]
label = Distribution Plot
default_height = 400
description = Show the output of DensityFunction.
search_fragment = | fit DensityFunction <field> [by "<fields>"] show_density=true show_options="feature_variables,split_by,params"

[HeatmapViz]
label = Heatmap Plot
default_height = 400
description = Show data values as colors in a table matrix.
search_fragment = | `confusionmatrix(<x_axis>, <y_axis>)`

[AnomalyViz]
label = Anomaly Detection Chart
default_height = 400
description = Show anomaly detection results with prediction intervals, zone boundaries, and highlighted anomaly regions.
search_fragment = | apply CDTSM <field> mode=anomaly
