"""
TA Builder — generates a Splunk Technology Add-on from extracted fields.
Outputs: props.conf, transforms.conf, data model JSON, and a deployable .tar.gz
"""
import os
import re
import json
import tarfile
import tempfile
import shutil
from datetime import datetime
from pathlib import Path


def sanitize_field_name(name: str) -> str:
    """Ensure field name is Splunk-safe."""
    return re.sub(r'[^a-zA-Z0-9_]', '_', name).lower()


def generate_props_conf(sourcetype: str, fields: list[dict]) -> str:
    """
    Generate props.conf with EXTRACT and SEDCMD entries.
    PII fields get a SEDCMD mask.
    """
    lines = [
        f"[{sourcetype}]",
        "# Auto-generated by Splunk Agentic Log Analyzer",
        f"# Generated: {datetime.utcnow().isoformat()}Z",
        "",
    ]

    for field in fields:
        name = sanitize_field_name(field["name"])
        regex = field["regex"]
        lines.append(f"EXTRACT-{name} = {regex}")

    lines.append("")

    # PII masking via SEDCMD
    for field in fields:
        if field.get("is_pii"):
            name = sanitize_field_name(field["name"])
            pii_type = field.get("pii_type", "sensitive")
            lines.append(f"# PII Field: {pii_type}")
            lines.append(f"SEDCMD-mask_{name} = s/(?P<{name}>[^\\s]+)/[REDACTED_{pii_type.upper()}]/g")

    return "\n".join(lines)


def generate_transforms_conf(sourcetype: str, fields: list[dict]) -> str:
    """
    Generate transforms.conf (used for lookup-based transforms if needed).
    """
    lines = [
        "# transforms.conf — Auto-generated by Splunk Agentic Log Analyzer",
        f"# Generated: {datetime.utcnow().isoformat()}Z",
        "",
        "# Field aliases for CIM compliance",
        f"[{sourcetype}_field_aliases]",
        "# Add field aliases below as needed",
        "",
    ]

    # Common CIM field mappings
    CIM_MAPPINGS = {
        "src_ip": "src",
        "dest_ip": "dest",
        "ip": "src",
        "user": "user",
        "username": "user",
        "status": "status",
        "method": "http_method",
        "url": "url",
        "duration": "duration",
        "level": "severity",
        "severity": "severity",
    }

    for field in fields:
        name = sanitize_field_name(field["name"])
        cim_name = CIM_MAPPINGS.get(name)
        if cim_name and cim_name != name:
            lines.append(f"# CIM: {name} -> {cim_name}")
            lines.append(f"FIELDALIAS-{name} = {name} AS {cim_name}")

    return "\n".join(lines)


def generate_data_model_json(sourcetype: str, fields: list[dict]) -> dict:
    """
    Generate a Splunk CIM-compatible data model JSON.
    """
    model_fields = []
    for field in fields:
        name = sanitize_field_name(field["name"])
        field_def = {
            "fieldName": name,
            "owner": f"BaseEvent.{name}",
            "type": "string",
            "fieldSearch": "",
            "required": False,
            "multivalue": False,
            "hidden": field.get("is_pii", False),
            "editable": True,
            "displayName": name.replace("_", " ").title(),
            "comment": field.get("description", ""),
        }
        if field.get("is_pii"):
            field_def["comment"] += f" [PII: {field.get('pii_type', 'sensitive')}]"
        model_fields.append(field_def)

    return {
        "modelName": f"TA_{sourcetype}",
        "displayName": f"TA {sourcetype.replace('_', ' ').title()}",
        "description": f"Auto-generated data model for {sourcetype}",
        "objectSummary": {
            "Event-Based": 1,
            "Transaction-Based": 0,
            "Search-Based": 0
        },
        "objects": [
            {
                "objectName": "BaseEvent",
                "displayName": "Base Event",
                "parentName": "BaseEvent",
                "tsidxNamespace": "default",
                "comment": f"Base events for {sourcetype}",
                "fields": model_fields,
                "calculations": [],
                "constraints": [
                    {"search": f"sourcetype={sourcetype}"}
                ],
                "lineage": "BaseEvent"
            }
        ],
        "acceleration": {
            "enabled": False,
            "earliestTime": "-7d",
            "cronSchedule": "*/5 * * * *"
        }
    }


def generate_app_conf(ta_name: str, version: str = "1.0.0") -> str:
    return f"""# app.conf — Auto-generated by Splunk Agentic Log Analyzer
[launcher]
author = Splunk Agentic Log Analyzer
description = Technology Add-on for automated log field extraction
version = {version}

[id]
name = {ta_name}
version = {version}

[ui]
is_visible = 1
label = {ta_name.replace('_', ' ').title()}

[install]
is_configured = 1
"""


def generate_readme(ta_name: str, sourcetype: str, fields: list[dict]) -> str:
    pii_fields = [f for f in fields if f.get("is_pii")]
    lines = [
        f"# {ta_name}",
        "",
        f"Auto-generated Splunk Technology Add-on for `{sourcetype}` logs.",
        "Generated by the **Splunk Agentic Log Analyzer** (hackathon project).",
        "",
        "## Extracted Fields",
        "",
        "| Field | Match Rate | PII | Description |",
        "|-------|-----------|-----|-------------|",
    ]
    for f in fields:
        pii = f"⚠️ {f.get('pii_type', '')}" if f.get("is_pii") else "✅ No"
        lines.append(f"| `{f['name']}` | {f.get('match_rate', 0):.1%} | {pii} | {f.get('description', '')} |")

    if pii_fields:
        lines += [
            "",
            "## ⚠️ PII Fields (Redaction Enabled)",
            "",
            "The following fields contain PII and are automatically masked via SEDCMD in props.conf:",
            "",
        ]
        for f in pii_fields:
            lines.append(f"- `{f['name']}` ({f.get('pii_type', 'sensitive')})")

    lines += [
        "",
        "## Installation",
        "",
        "1. Extract to `$SPLUNK_HOME/etc/apps/`",
        "2. Restart Splunk or reload the app",
        f"3. Set `sourcetype = {sourcetype}` on your data inputs",
        "",
        "## Files",
        "- `default/props.conf` — Field extraction (EXTRACT) and PII masking (SEDCMD)",
        "- `default/transforms.conf` — CIM field aliases",
        "- `default/data/models/` — CIM data model",
    ]
    return "\n".join(lines)


def build_ta(
    ta_name: str,
    sourcetype: str,
    fields: list[dict],
    output_dir: str = "/tmp",
) -> str:
    """
    Build a complete TA directory and package it as a .tar.gz.
    Returns the path to the .tar.gz file.
    """
    # Create TA directory structure
    with tempfile.TemporaryDirectory() as tmpdir:
        ta_dir = Path(tmpdir) / ta_name
        (ta_dir / "default" / "data" / "models").mkdir(parents=True)
        (ta_dir / "metadata").mkdir()

        # Write props.conf
        (ta_dir / "default" / "props.conf").write_text(
            generate_props_conf(sourcetype, fields)
        )

        # Write transforms.conf
        (ta_dir / "default" / "transforms.conf").write_text(
            generate_transforms_conf(sourcetype, fields)
        )

        # Write data model JSON
        model = generate_data_model_json(sourcetype, fields)
        (ta_dir / "default" / "data" / "models" / f"{ta_name}.json").write_text(
            json.dumps(model, indent=2)
        )

        # Write app.conf
        (ta_dir / "default" / "app.conf").write_text(
            generate_app_conf(ta_name)
        )

        # Write README
        (ta_dir / "README.md").write_text(
            generate_readme(ta_name, sourcetype, fields)
        )

        # Write metadata/default.meta
        (ta_dir / "metadata" / "default.meta").write_text(
            f"[]\\nexport = system\\n"
        )

        # Package as .tar.gz
        output_path = os.path.join(output_dir, f"{ta_name}.tar.gz")
        with tarfile.open(output_path, "w:gz") as tar:
            tar.add(ta_dir, arcname=ta_name)

    return output_path


def get_ta_preview(sourcetype: str, fields: list[dict]) -> dict:
    """
    Return a preview of what the TA will contain (for the API response).
    """
    return {
        "sourcetype": sourcetype,
        "props_conf": generate_props_conf(sourcetype, fields),
        "transforms_conf": generate_transforms_conf(sourcetype, fields),
        "data_model": generate_data_model_json(sourcetype, fields),
        "field_count": len(fields),
        "pii_field_count": sum(1 for f in fields if f.get("is_pii")),
    }
