# Splunk app configuration file

[id]
name = Splunk_MCP_Server
version = 1.2.0

[package]
id = Splunk_MCP_Server
check_for_updates = 1

[install]
build = 083fe7fe-37176485
is_configured = 0
state = enabled

[ui]
is_visible = 1
label = Splunk MCP Server

[launcher]
author = ML Dev <mlsupport@splunk.com>
description = MCP server for Splunk
version = 1.2.0

[triggers]
reload.mcp = simple
