# Allows user connect to MCP server and run tools
[capability::mcp_tool_execute]
[capability::mcp_tool_admin]

[role_admin]
mcp_tool_execute = enabled
mcp_tool_admin = enabled

[role_sc_admin]
mcp_tool_execute = enabled
mcp_tool_admin = enabled
