[mcp_server]
SHOULD_LINEMERGE = false
TIME_PREFIX = \"time\":\s*\"
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%Z
TZ = UTC
MAX_TIMESTAMP_LOOKAHEAD = 30
TRUNCATE = 100000
KV_MODE = json

[mcp_monitoring_dashboard]
SHOULD_LINEMERGE = false
TIME_PREFIX = \"time\":\s*\"
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%Z
TZ = UTC
MAX_TIMESTAMP_LOOKAHEAD = 30
TRUNCATE = 100000
KV_MODE = json

