[Splunk MCP Server - Telemetry]
action.email.sendresults                   = 0
action.outputtelemetry                     = 1
action.outputtelemetry.param.anonymous     = 1
action.outputtelemetry.param.support       = 1
action.outputtelemetry.param.optinrequired = 3
action.outputtelemetry.param.component     = app.Splunk_MCP_Server.tool_usage
action.outputtelemetry.param.input         = data
action.outputtelemetry.param.type          = aggregate
alert.track                                = false
counttype                                  = number of events
relation                                   = greater than
quantity                                   = 0
cron_schedule                              = 33 3 * * *
description                                = Sends anonymous operational data
disabled                                   = False
dispatch.earliest_time                     = -1d@d
dispatch.latest_time                       = @d
enableSched                                = 1
is_visible                                 = false
schedule_window                            = auto
search                                     = index=_internal source="*mcp_server.log*" \
| spath \
| search operation_type=rpc_request operation_phase=end \
| eval tool_name=coalesce(tool_name,"n/a") \
| eval user_id=coalesce(user_id,"n/a") \
| eval rpc_method=coalesce(rpc_method,"n/a") \
| eval status=coalesce(status,"n/a") \
| eval app_version=coalesce(app_version,"n/a") \
| eval auth_method=coalesce(auth_method,"n/a") \
| stats count avg(execution_time_seconds) as avg_exec_time min(execution_time_seconds) as min_exec_time max(execution_time_seconds) as max_exec_time by user_id, rpc_method, tool_name, status, app_version, auth_method \
| eval avg_exec_time=round(avg_exec_time, 3), min_exec_time=round(min_exec_time, 3), max_exec_time=round(max_exec_time, 3) \
| makejson output=data \
| table data