[expose:mcp]
pattern = mcp
methods = POST

[expose:mcp_tools]
pattern = mcp_tools
methods = POST, DELETE, GET, PUT

[expose:mcp_token]
methods = GET,POST
pattern = mcp_token

[expose:mcp_rate_limits]
methods = GET, POST
pattern = mcp_rate_limits

[expose:mcp_tools_collisions]
pattern = mcp_tools/collisions
methods = POST

[expose:mcp_guardrails]
pattern = mcp_guardrails
methods = GET, POST

[expose:oauth_protected_resource]
pattern = .well-known/oauth-protected-resource
methods = GET
